version: 2
python:
  install:
    - method: pip
    - path: .
    - extra_requirements:
      - sphinx
      - sphinx-book-theme
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
  jobs:
    pre_build:
      - [[ -e ./generate_docs.sh ]] && . ./generate_docs.sh || true
      - [[ -e ./scripts/generate_docs.sh ]] && . ./scripts/generate_docs.sh || true
