name: neurox-toolkit
channels:
  - defaults
dependencies:
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - backcall=0.2.0
  - bleach=3.3.0
  - ca-certificates=2021.5.25
  - certifi=2021.5.30
  - cffi=1.14.5
  - dbus=1.13.18
  - decorator=5.0.9
  - defusedxml=0.7.1
  - entrypoints=0.3
  - expat=2.4.1
  - gettext=0.21.0
  - glib=2.68.2
  - icu=58.2
  - importlib_metadata=3.10.0
  - ipykernel=5.3.4
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.17.0
  - jinja2=3.0.0
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.12
  - jupyter_console=6.4.0
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - libcxx=10.0.0
  - libffi=3.3
  - conda-forge::libiconv=1.16
  - libpng=1.6.37
  - libsodium=1.0.18
  - libxml2=2.9.10
  - llvm-openmp=10.0.0
  - markupsafe=2.0.1
  - mistune=0.8.4
  - nb_conda_kernels=2.3.1
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - notebook=6.4.0
  - openssl=1.1.1k
  - packaging=20.9
  - pandoc=2.12
  - pandocfilters=1.4.3
  - parso=0.8.2
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.1.1
  - prometheus_client=0.10.1
  - prompt-toolkit=3.0.17
  - prompt_toolkit=3.0.17
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pygments=2.9.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - python=3.6.13
  - python-dateutil=2.8.1
  - pyzmq=20.0.0
  - qt=5.9.7
  - qtconsole=5.0.3
  - qtpy=1.9.0
  - readline=8.1
  - send2trash=1.5.0
  - setuptools=52.0.0
  - sip=4.19.8
  - sqlite=3.35.4
  - terminado=0.9.4
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.1
  - traitlets=4.3.3
  - typing_extensions=3.7.4.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.4.1
  - zlib=1.2.11
  - pip:
    - cached-property==1.5.2
    - chardet==4.0.0
    - click==8.0.1
    - colorama==0.4.4
    - coverage==5.5
    - cycler==0.10.0
    - dataclasses==0.8
    - filelock==3.0.12
    - green==3.2.6
    - h5py==3.1.0
    - huggingface-hub==0.0.8
    - idna==2.10
    - imbalanced-learn==0.8.0
    - imblearn==0.0
    - importlib-metadata==4.5.0
    - joblib==1.0.1
    - kiwisolver==1.3.1
    - lxml==4.6.3
    - matplotlib==3.3.4
    - numpy==1.19.5
    - pandas==1.1.5
    - pillow==8.2.0
    - pytz==2021.1
    - regex==2021.4.4
    - requests==2.25.1
    - sacremoses==0.0.45
    - scikit-learn==0.24.2
    - scipy==1.5.4
    - seaborn==0.11.1
    - six==1.16.0
    - sklearn==0.0
    - svgwrite==1.4.1
    - threadpoolctl==2.1.0
    - tokenizers==0.10.3
    - torch==1.8.1
    - tqdm==4.61.0
    - transformers==4.6.1
    - typing-extensions==3.10.0.0
    - unidecode==1.2.0
    - urllib3==1.26.5

